// src/pages/terms.js
import React from 'react';
import Head from 'next/head';
import Link from 'next/link';
import MainLayout from '../layouts/MainLayout';

const Section = ({ n, title, children }) => (
  <section className="mb-10">
    <h2 className="flex items-baseline gap-3 text-lg font-semibold mb-3">
      <span className="font-mono text-sm accent-text">{n}</span> {title}
    </h2>
    <div className="space-y-3 text-gray-600 dark:text-gray-400 leading-relaxed">{children}</div>
  </section>
);

const Terms = () => (
  <MainLayout>
    <Head>
      <title>Terms | Manjunathan Radhakrishnan</title>
      <meta name="description" content="Terms of use for manjunathan.me and the Sun CLI." />
    </Head>

    <div className="container-narrow pt-36 pb-20">
      <p className="label-mono mb-2">~/terms</p>
      <h1 className="display text-4xl md:text-5xl mb-3">Terms</h1>
      <p className="text-gray-500 dark:text-gray-400 mb-12">
        Plain-English terms for this site and the <Link href="/cli" className="accent-text hover:underline">Sun CLI</Link>. Last updated May 2026.
      </p>

      <Section n="01" title="The basics">
        <p>This is my personal website. By browsing it or using the CLI, you agree to these terms. If you don't agree, no hard feelings — just don't use it.</p>
      </Section>

      <Section n="02" title="The Sun CLI">
        <p>"Sun" is an AI assistant that answers questions about me. Its replies are <strong>generated by Google Gemini</strong> from a profile grounded in my resume. It can still be wrong, incomplete, or out of date.</p>
        <p>Treat its answers as a helpful starting point, not as professional, legal, financial, or hiring advice — and not as a binding statement from me.</p>
      </Section>

      <Section n="03" title="Acceptable use">
        <p>Don't try to break, overload, scrape, or abuse the CLI or its backend, and don't use it to generate harmful or unlawful content. I rate-limit requests and may cut off abuse.</p>
      </Section>

      <Section n="04" title="Content & IP">
        <p>The writing, projects, and code samples here are mine unless noted. The Omnitrix and Ben 10 are trademarks of their respective owners — used here purely as fan art, with no affiliation implied.</p>
      </Section>

      <Section n="05" title="No warranties">
        <p>Everything is provided "as is", without warranties of any kind. I'm not liable for any loss arising from using the site or the CLI.</p>
      </Section>

      <Section n="06" title="Changes & contact">
        <p>I may update these terms as the site evolves. Questions? <a href="mailto:manjunathan.ai02@gmail.com" className="accent-text hover:underline">manjunathan.ai02@gmail.com</a>. See also the <Link href="/privacy" className="accent-text hover:underline">Privacy Policy</Link>.</p>
      </Section>
    </div>
  </MainLayout>
);

export default Terms;
